### ISSUE TITLE
Поставить спрайт obj/machinery/doppler_array

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#101]
По неясным мне причинам, бейцы удалили его спрайт и убрали его с карты. Если с ним все нормально, нужно просто его впилить, но черт знает. Может бейцы его сломали. Я положил его спрайты в research.dmi, там же где у Ребея, где, кстати, спрайты у него были и работали.

**Comment by PlinHost** [comment]
Требует #15
