### ISSUE TITLE
багогарпун

### ISSUE THREAD

**Issue by EkuDza** [Endless-Horizon/CEV-Eris#131]
Заметил пару багов у этого говнеца, надо пофиксить:
При попытке засунуть гарпун в сумку на персонаже, можно стать единым, например, с трубой.

**Comment by SpadesSlick** [comment]
> RandomColonist: Прицелился ресивом на чувака внизу - его видимо под меня портануло.
> RandomColonist: А не на меня.
> RandomColonist: Запили работу с опенспейсом.
> RandomColonist: Я телепортнулся на воздух.
