### ISSUE TITLE
Возродить человечество

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#19]
Портировать пропорции тел с Ребея, поддержку одежды для них. Допилить необходимые оверлеи, вроде оверлеев повреждений, husk, и прочие вещи, которые не успели сделать на Ребее. [Работа над ними началась тут.](https://bitbucket.org/animusstations/rebay/commits/7b769f9f14160c990b6b53e519cd668f6778b5ea)

Исуй должен быть закрыт только после закрытия исуя #214

WIP:
- [x] Убрать постфикс _s для униформ.
- [x] Стандартизировать код униформы: icon_state - на теле, item_state - в руках.
- [x] Поправить иконки маек.
- [x] Добавить иконки для типов тел.
- [x] Разблокировать майки для нестандартных тел (тонкота, толстота).
- [x] Адаптировать протезы под нестандартные тела (тонкота, толстота).

**Comment by LethalGhost** [comment]
WIP:
+ Проверить иконки маек.

**Comment by LethalGhost** [comment]
Более или менее завершено. Проверить протезы отдельно.
