### ISSUE TITLE
Гейские фичи Поляриса в сетап

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#229]
https://gyazo.com/02c58752200ed3d3f36b7b77911a9671
Разделить биологический пол, и пол определяемый внешним видом.

**Comment by Euronem** [comment]
Худшая идея бейцев за последние два года. Она не стоит портирования.

**Comment by SpadesSlick** [comment]
Но это киберпанковое будущее, и появление хуйпонятных созданий более чем уместно.

**Comment by Euronem** [comment]
>хуйпонятных.
Одно дело, когда у них будет кибенетический хуй из космических материалов со встроенным ИИ.
А другое дело, когда это - обыкновенные членодевки, коих и сегодня полным полно.

**Comment by SpadesSlick** [comment]
Хорошо. Мейби стоит просто сделать галку в сетапе, которая будет делать внешний вид "нейтральным", с невозможностью определить пол просто так.

**Comment by SpadesSlick** [comment]
Вернемся к этому потом и с другого подхода.
