### ISSUE TITLE
Портировать свет с VG

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#237]
Гунский свет, который был приведен в порядок, и относительно откалиброван на VG билде, так что смотрится вполне адекватно на билдах основанных на ТГ.

Его важность обуславливается тем, что большая часть нашей работы была со спрайтами. Хороший свет попросту умножит эту работу, сделает графон неповторимым и охуенным, что даст высокую популярность сборки на начальном этапе.

**Comment by ModernViolence** [comment]
Параллельно или перед этим разобраться, нужен ли VG свет целиком - #253

**Comment by SpadesSlick** [comment]
В итоге мы спиздили его у Тау.
