### ISSUE TITLE
Определиться с тем, какие звуки дальше делать (делать ли?)

### ISSUE THREAD

**Issue by ModernViolence** [Endless-Horizon/CEV-Eris#256]
1. Посмотреть, как станция звучит сейчас, после трех волн добавления новых звуков. Какафонии быть не должно.
2. Решить, каких еще звуков не хватает.

**Comment by SpadesSlick** [comment]
1. Нормально звучит. Мы не вводили зацикленные звуки для машинерии, поэтому звучать оно будет только при деятельности игроков, какафонии нет.
2. Совершенно точно нам необходимы звуки ходьбы. В третьей волне не были законченны звуки таскания всяческих клозетов, и зажигалки со спичками. Звуки ходьбы войдут в "третью с половиной" волну, и на этом пока можно успокоится со звуками.
