### ISSUE TITLE
Проблемы с опенспейсами

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#299]
- [ ] Бластдуры открытые не дают падать вниз, хотя должны.
![image](https://cloud.githubusercontent.com/assets/9161564/20249278/30be8c4a-aa07-11e6-9cdf-a8c2eaea085f.png)

- [ ] Аналогично с перилами.
![image](https://cloud.githubusercontent.com/assets/9161564/20249283/43c2542a-aa07-11e6-8d42-a4b5b19c7305.png)

- [x] Часто, при неясных обстоятельствах, лестницы блокируют проход наверх.
![image](https://cloud.githubusercontent.com/assets/9161564/20249326/493c7a42-aa08-11e6-946a-472f1be5c5d2.png)

**Comment by SpadesSlick** [comment]
Лестницы проще портировать с Ребея полностью, чем фиксить текущие, скорее всего.

**Comment by EkuDza** [comment]
Не понял проблему с перилами...

**Comment by SpadesSlick** [comment]
Проблема уже в другом, иссуй не актуален.
