### ISSUE TITLE
Возможность крафта и разбора кетволков

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#319]
Кликом родсами на андерплатинг создание, фомкой на кетволк - разбор до родсов.

Клик родсами по космосу и опенспесу создает латайсы, а клик родсами по этим латайсам должен создавать кетволки. По идее, это не конфликтует с другими рецептами.

**Comment by TheOneForgotten** [comment]
https://github.com/Endless-Horizon/CEV-Eris/pull/573
