### ISSUE TITLE
В космосе никто не услышит твой крик

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#336]
Судно частное, свободное, и вообще находится как бы в походе, в глубоком космосе. Никакого ЕРТ быть не может. Необходимо выпилить кнопку присоединения к ЕРТ в окне команд, сам вызов ЕРТешников с судна, а так же закомментить прочий ненужный мусор, который останется после всего этого.

**Comment by fey** [comment]
Добавить маячок бедствия, сделать эвент космо-кочевников, которые "случайно" натыкаются на корабль.

**Comment by SpadesSlick** [comment]
Тестовый комментарий.
