### ISSUE TITLE
Всю одежду необходимо почистить вилкой

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#361]
- [x] # **Тонкие женские**
**Женские тонкие униформы.** Они слишком толстые для этой пропорции, в основном в руках, и окаймляют тела неправильно. Это очень часто видно на броне, которая делает это нормально. Кроме этого, есть еще пара ошибок.
![image](https://cloud.githubusercontent.com/assets/9161564/21679582/fff3d1d8-d355-11e6-8976-6e3b3fc43399.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679588/02425324-d356-11e6-9109-0d72667e4077.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679593/0551b974-d356-11e6-9980-f1a20558a7c6.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679609/0df4eb96-d356-11e6-8e4f-b50c70b75c97.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21680009/0fdc27e2-d358-11e6-847f-77cd2fe13d8e.png)
**Другие ошибки.**
![image](https://cloud.githubusercontent.com/assets/9161564/21679636/25fdae94-d356-11e6-9bc4-8759595336cb.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679648/3bd56702-d356-11e6-97e2-bd8dd4796b72.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679651/3dcfd718-d356-11e6-84ac-2f8d7282938d.png)
- [ ] **Женские тонкие рюкзаки.** Кажется, мы забыли их адаптировать вообще.
![image](https://cloud.githubusercontent.com/assets/9161564/21679674/603fc07e-d356-11e6-8739-50b591cc642a.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679676/6378407c-d356-11e6-9e82-dde0996c0428.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679684/6c6f0c88-d356-11e6-897d-45f2998f42cc.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21679686/6f389812-d356-11e6-9a12-a086b68b52d4.png)
- [ ] **Женские тонкие сьюты и прочее.**
![image](https://cloud.githubusercontent.com/assets/9161564/21679641/2d04b4e4-d356-11e6-9d24-68b540ccdd10.png)
Не нужно прорисовывать фартук между ног, там нет просвета.
![image](https://cloud.githubusercontent.com/assets/9161564/21691827/3fd4bab2-d38b-11e6-8af4-d8c111e4cd6f.png)
- [ ] # **Тонкие мужские**
По сути, аналогичные проблемы.
![image](https://cloud.githubusercontent.com/assets/9161564/21692704/2a332d70-d38f-11e6-8b4a-9f45f2c4bb0c.png)
По идее, куртка должна быть закрыта.
![image](https://cloud.githubusercontent.com/assets/9161564/21693459/174b1ff8-d392-11e6-8388-c3c84a0d4e52.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21693468/1f3fe482-d392-11e6-9593-ed615a93458f.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21693469/216d358e-d392-11e6-8f75-24b9b7743798.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21693610/a8635032-d392-11e6-9ca5-2bb8c2ab9f1a.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21693616/a9dc9a04-d392-11e6-978a-2651e9f9b0cf.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21693621/abfe22bc-d392-11e6-9f9b-824b5d66462e.png)
- [x] # **Жирные**
Не хватает пикселя, еще угадай где, в джампсьютах, или в обуви.
![image](https://cloud.githubusercontent.com/assets/9161564/21693654/c7cb94e8-d392-11e6-885f-b0c3ae74c23b.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21693767/3766db46-d393-11e6-9cff-29f8745281c4.png)
Эти рюкзаки надо аннигилировать.
![image](https://cloud.githubusercontent.com/assets/9161564/21693775/459745f2-d393-11e6-8d8e-f442cd65842a.png)
Заплатка на костюме проебана, и она проебана везде, хотя есть на виде спереди.
![image](https://cloud.githubusercontent.com/assets/9161564/21693802/6621cc2a-d393-11e6-974a-3d5aabdeb6ed.png)
- [x] # **Обычные женские**
Снова, эта куртка должна быть закрытой.
![image](https://cloud.githubusercontent.com/assets/9161564/21693864/9d78cda4-d393-11e6-95e7-c935ceadd036.png)
Грудь вылезает за броник.
![image](https://cloud.githubusercontent.com/assets/9161564/21693874/a8355c8a-d393-11e6-88ac-28c45bae62b3.png)
Пиксель ноги виден из ботинка.
![image](https://cloud.githubusercontent.com/assets/9161564/21693887/b3d8164a-d393-11e6-8bca-bdc4bfb46b14.png)

**Comment by SpadesSlick** [comment]
Обновил.

**Comment by MyLittleLoly** [comment]
![image](https://cloud.githubusercontent.com/assets/3694552/21964463/7d68c4ac-db5d-11e6-8eeb-cf49fa91c2c5.png) - выпирает грудь
![image](https://cloud.githubusercontent.com/assets/3694552/21964461/779517c4-db5d-11e6-830c-48297037d1d9.png)
Чисти, сука, чисти.
