### ISSUE TITLE
Эмиттеры в РнД ломают стену, вызывая разгерметизацию

### ISSUE THREAD

**Issue by MyLittleLoly** [Endless-Horizon/CEV-Eris#375]
![image](https://cloud.githubusercontent.com/assets/3694552/21964433/1f2326bc-db5d-11e6-9bd8-ae4543ce46b5.png)
Судя по словам Летала, на Бее это норма, но оно слишком быстро ломается.

**Comment by SpadesSlick** [comment]
На бее оно дырявит стену в астроид. Так как там камень, то ничего страшного не происходит. Тут же нужно что-то придумать.

**Comment by Strinkor** [comment]
Есть 2 костыля, так-то. Или сделать стеночку indestructable или же отпилить всем эмитерам такой скилл.

**Comment by SpadesSlick** [comment]
Нет, это слишком костыльно. Лучше всего просто укрепить эту часть вторым слоем. От дебилов не спасет, но хватит для того, чтобы заделать в случает чего.

**Comment by SpadesSlick** [comment]
![image](https://cloud.githubusercontent.com/assets/9161564/21967117/e589342a-db91-11e6-9553-d65f556649ae.png)
