### ISSUE TITLE
Водокалий унерфан

### ISSUE THREAD

**Issue by ucnaHez** [Endless-Horizon/CEV-Eris#380]
съел таблетку того и другого - даже не кнокнуло.

**Comment by SpadesSlick** [comment]
Реакция то пошла?

**Comment by ucnaHez** [comment]
Да, звук бульканья и взрыва был.

**Comment by SpadesSlick** [comment]
ADMIN LOG: Explosion with size (-1, -1, 0) in area Chemistry (68,83,4)
Если 60 на 60 в теле.
ADMIN LOG: Explosion with size (0, 1, 3) in area Chemistry (68,82,4)
Если 60 на 60 в колбах.

В колбах нормально, в теле нужно бафнуть.
