### ISSUE TITLE
Добавить больше навигации

### ISSUE THREAD

**Issue by MyLittleLoly** [Endless-Horizon/CEV-Eris#386]
На станции маловато табличек, указывающие на важные публичные места, как, например на картинке. Слева бар, справа библиотека.
![image](https://cloud.githubusercontent.com/assets/3694552/21965565/b36b4622-db73-11e6-85b3-746588e18cf8.png)

**Comment by SpadesSlick** [comment]
![image](https://cloud.githubusercontent.com/assets/9161564/22404328/c85b2a58-e63f-11e6-9f92-2105728d6555.png)
Нужно нарисовать кучу новых знаков, потому что текущие либо ресайзнутое говно, либо малоюзабельное говно.

**Comment by SpadesSlick** [comment]
Больше табличек для отделов со стрелками, размещаемые на стенах.
![image](https://cloud.githubusercontent.com/assets/9161564/22484755/e2f0caf0-e813-11e6-8f0c-9dc24d3ccd4f.png)
По желанию можно перерисовать их с нуля, добавить таблички для следующих отсеков:
**Мостик** - да, главную табличку для всего отдела тоже нужно, как и те что будут внутри него.
ИИ
Телекомы
Зал совещаний глав
**Охрана**
Арсенал
Карцер
Кабинет коммандера
**Медбей**
Химия
Генетика
Вирология
Морг
Операционная
**Научный отдел**
Ксенобиология
Аномалистика
Доки для научного шаттла
Хранилище токсинов
Исследование токсинов
Роботехника
РНД
**Гражданские отсеки**
Бар
Ассистентская
Библиотека
Церковь
EVA
**Карго**
Доки для шахтерской баржи
Доки для шаттла карго
Почта и сортировочная
**Инженерный**
Атмос
Дроны
Двигатель

**Comment by SpadesSlick** [comment]
Done.
