### ISSUE TITLE
Сетап пидорасит

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#390]
- [ ] runtime error: bad index
proc name: OnTopic (/datum/category_item/player_setup_item/general/equipment/OnTopic)
source file: 04_equipment.dm,58

- [ ]  runtime error: type mismatch: null -= "CHAT_OOC"
proc name: set preference (/client/proc/set_preference)
source file: 02_settings.dm,103

**Comment by fluorescent-net** [comment]
https://github.com/Endless-Horizon/CEV-Eris/pull/421

**Comment by SpadesSlick** [comment]
Протестировал, рантаймов больше нет, все хорошо.
