### ISSUE TITLE
Сломанные алиены

### ISSUE THREAD

**Issue by MyLittleLoly** [Endless-Horizon/CEV-Eris#391]
![image](https://cloud.githubusercontent.com/assets/3694552/21965734/219a95dc-db77-11e6-89de-30117c906669.png) ![image](https://cloud.githubusercontent.com/assets/3694552/21965736/26fcbbfe-db77-11e6-9528-e1fca0a715cf.png)

[23:04] Luna Dark: С королевой такое же.
[23:05] Luna Dark: Я эволюционировала.
[23:05] Luna Dark: Еще плазма не копится.
[23:05] Luna Dark: И трава не распространяется.

Мне кажется там алиенов совсем сломали. Если не будем выпиливать, то стоит пофиксить.

**Comment by MyLittleLoly** [comment]
Так же у алиенов немного обрезанный интерфейс, который выглядит ужасно
![image](https://cloud.githubusercontent.com/assets/3694552/21965872/a37943ee-db79-11e6-9d78-fc4a9336b797.png)

**Comment by LethalGhost** [comment]
@MyLittleLoly, плазма и трава не растет из-за того, что алиенов надо включать педальной кнопкой.

**Comment by SpadesSlick** [comment]
Это как-то тупо. Я могу понять отключение рандомного ивента с алиенами, но рубить к чертям весь механ?

**Comment by LethalGhost** [comment]
@SpadesSlick, еще на Блэках так было. До сих пор так.
