### ISSUE TITLE
Террабайты ганпрона захватили репозиторий

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#395]
У людей клиенты подвисают при стрельбе от таких размеров звуков, ну это чот пиздец.
![image](https://cloud.githubusercontent.com/assets/9161564/21966113/647aeba2-db7e-11e6-90de-3ff707a7d689.png)
Стандартные игровые звуки весят раз в 100 меньше.
![image](https://cloud.githubusercontent.com/assets/9161564/21966115/808118e4-db7e-11e6-9416-7205fc2fa1b0.png)

**Comment by alexix1989** [comment]
Надо стать шакалами
