### ISSUE TITLE
Костыльный лифт

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#40]
В карго Эрис есть лифт, работающий на коде шаттлов. Нужно посмотреть его применимость к текущему коду, и подумать, можно ли сделать его лучше.

**Comment by FinnTheTurtle** [comment]
Насколько я помню, на Бэе есть что-то такое. Не помню, как он работает, но, тем не менее. А ещё, он бы пригодился в какой-нибудь инженерке, чтобы канистры лестницами не таскать.

**Comment by SpadesSlick** [comment]
We dont need it now.
