### ISSUE TITLE
Убрать флаворы на каждый палец, и иные охуительные истории с Бея

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#403]
- [ ] ![image](https://cloud.githubusercontent.com/assets/9161564/22016385/2beb1c14-dcb7-11e6-816e-965e28bbf5b0.png)Убрать саму подменюшку, оставить только один флавор, сделать его невидимым при скрытии лица (потому что сейчас там дженирал флавор для роста, и виден всегда и всем). Увеличить число символов в новом, общем флаворе. Флаворы боргов не трогать, пока что.

- [x] ![image](https://cloud.githubusercontent.com/assets/9161564/22016548/c09221f0-dcb7-11e6-8105-e23bcb174215.png)Эта информация более не является актуальной для нашего бека. Нужно выпилить ее всю, ровно как и код ссылающийся на нее. Совершенно точно что лояльность корпорации определяет зарплату, и еще пару вещей, вроде информации трейторам, что этот человек может оказаться полезен. Так как судно частное, это все не подходит нам.

- [x] ![image](https://cloud.githubusercontent.com/assets/9161564/22016729/544c5334-dcb8-11e6-8330-35951a779b13.png)Способ прибытия у нас теперь только один (крио), так что стоит выпилить сам выбор.

- [x] ![image](https://cloud.githubusercontent.com/assets/9161564/22016787/7f038930-dcb8-11e6-98c5-36f19f775cd7.png)![image](https://cloud.githubusercontent.com/assets/9161564/22016817/a8effe04-dcb8-11e6-94cd-2cd33cbfe01e.png)

**Comment by fluorescent-net** [comment]
https://github.com/Endless-Horizon/CEV-Eris/pull/416
