### ISSUE TITLE
Добить базовые расы людей.

### ISSUE THREAD

**Issue by LethalGhost** [Endless-Horizon/CEV-Eris#407]
- [x] Убрать ВЛ на расы (code/game/jobs/whitelist.dm) и его использование.
- [x] Убрать флаги рас для химии.
- [x] Убрать код рас Котов, Ящеров, Деревьев, Скреллов.
- [ ] Удалить неиспользуемые спрайты рас (icons/mob/human_races/*).
- [ ] Удалить неиспользуемые дополнительные спрайты рас (icons/effects/species.dmi).

**Comment by fluorescent-net** [comment]
https://github.com/Endless-Horizon/CEV-Eris/pull/418
По первым трём пунктам можно мёржить.
