### ISSUE TITLE
Портировать свет /VG/(он же гунский) с Бея Тау для тестов

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#410]
На данный момент ВГшный свет смотрится лучше всех остальных непотайловых, и он уже адаптирован под Бей у них. Проще всего взять оттуда.

У некоторых он пока вызывает сомнения, так что тесты покажут его необходимость. Лично мне кажется, что он отлично зайдет на наши спрайты.

https://github.com/TauCetiStation/TauCetiClassic

**Comment by Euronem** [comment]
Тебе белых пятен мало?
Хуй знает, короче.

**Comment by SpadesSlick** [comment]
Каких белых пятен?

**Comment by Euronem** [comment]
На стенах висят "куски" света.

**Comment by SpadesSlick** [comment]
Ну а сейчас на стенах висят квадраты света видные из техов, которые привычны нам просто потому, что замылили глаза за все эти годы. Но на самом деле оно так же хуево.
