### ISSUE TITLE
Паралакс космоса со своей картинкой

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#444]
Необходимо закончить его, и заставить работать нормально. Однако наличие этажей, и то что космос должен работать как опенспейсы вызывает сложности.
![image](https://cloud.githubusercontent.com/assets/9161564/22499351/45824a3a-e86f-11e6-8456-08d9ba615c7a.png)

**Comment by MyLittleLoly** [comment]
https://github.com/d3athrow/vgstation13/commit/cfef0afef0dc24f6c65ea75f485f27dc2965bf71
https://github.com/FTL13/FTL13/commit/eae5778805137e8486e659a420c0c993c5fa5321
