### ISSUE TITLE
Parallax is broken

### ISSUE THREAD

**Issue by Euronem** [Endless-Horizon/CEV-Eris#488]
It is totally white if player is inside closet/disposals/etc.

**Comment by fluorescent-net** [comment]
Периодически картинка паралакс движется рывками.

**Comment by SpadesSlick** [comment]
@fluorescent-net это связано с пролагом бея при движении, и к паралаксу не относится.

**Comment by SpadesSlick** [comment]
![image](https://cloud.githubusercontent.com/assets/9161564/22865198/23b68b3c-f170-11e6-824e-9e09081a16a3.png)
Отображается таким при джампе, пропадает при движении.

**Comment by fluorescent-net** [comment]
![image](https://i.gyazo.com/f8c9aadb942f8b090c73204198a4ddc9.png)
Trying to use security camera network.

**Comment by SpadesSlick** [comment]
We need to update paralax everytime we teleport, that should fix a lot of those bugs.
