### ISSUE TITLE
Мусорную рубу проебалей

### ISSUE THREAD

**Issue by Euronem** [Endless-Horizon/CEV-Eris#490]
77.37.2
![](https://images.discordapp.net/.eJwFwdENhCAMANBdGIAWKIhuQ5CgOaUEavy43O733lc941KbOkT63AD2c2Yeu57CI9WiK3O9Surn1JlvSCIpH3dpMsEGT8ZYj46MJ7e6ADaiwRhMDLTQgrgiPO3T-G26t6p-fwSLIss.CZ3oilUlCuOEcJ2UYGFcxQA3hTw?width=479&height=441)

**Comment by SpadesSlick** [comment]
Это нормально, нам нужно переделать сортировочные трубы на Бее вообще, и уже потом их ставить на карту.

**Comment by SpadesSlick** [comment]
Они почти везде такие.
