### ISSUE TITLE
Звуки выстрелов так же проебалей

### ISSUE THREAD

**Issue by Euronem** [Endless-Horizon/CEV-Eris#491]
Они либо проигрываются на долю секунды, либо их вообще нет. Страдает все оружие с мочелазерами, за огнестрелом не замечал

**Comment by fluorescent-net** [comment]
Встречал и у огнестрела, только там звуки выстрелов были обрывками.

**Comment by SpadesSlick** [comment]
Это случилось после выпиливания эха. Может его криво выпилили?

**Comment by SpadesSlick** [comment]
Request for Help:: AllahBoom/(Nucky Thompson)(?) (PP) (VV) (SM) (JMP) (CA): При работе эммитра - выключаются и больше не воспроизводятся ваши треки.
Request for Help:: AllahBoom/(Nucky Thompson)(?) (PP) (VV) (SM) (JMP) (CA): И у самого эммитра нет звка

**Comment by fluorescent-net** [comment]
Начал стрелять - эмбиент со станции пропал полностью. То же самое для музыки, которую проигрывали педально, в логах видел, что включали, а сам не слышал.

**Comment by SpadesSlick** [comment]
Реверт энвайромента их пофиксил.
