### ISSUE TITLE
Странные стекла по бокам от обычных стекол 

### ISSUE THREAD

**Issue by Euronem** [Endless-Horizon/CEV-Eris#495]
![default](https://cloud.githubusercontent.com/assets/17518355/22858223/c8db30ee-f0c7-11e6-8152-dba802eee65f.png)

**Comment by fluorescent-net** [comment]
Встречаются по всей станции, необходим беспрецендентный delet this.

**Comment by SpadesSlick** [comment]
Я это добавил для усиление, но если не нравится, могу и спилить, не принципиально.
