### ISSUE TITLE
Openspace doesn't update

### ISSUE THREAD

**Issue by fluorescent-net** [Endless-Horizon/CEV-Eris#500]
If tile is blown up black openspace is created which doesn't show anything below it.
![](https://cdn.discordapp.com/attachments/265411250341543936/280113954716516353/unknown.png)
![](https://i.gyazo.com/6a2e8a8dcd9b7bff323ff0dd223d64d7.png)

**Comment by SpadesSlick** [comment]
Проблема заключается в том, что они для турфов обновляются крайне неохотно вообще, не только после взрыва.

**Comment by fluorescent-net** [comment]
Опенспейс вообще не обновляется, походу.
Взрывал под опенспейсом. На уровне выше ничего не меняется в плане отображения.

**Comment by SpadesSlick** [comment]
We fix it in #656.
