### ISSUE TITLE
Носки и нижнее белье из сетапа не работает

### ISSUE THREAD

**Issue by fluorescent-net** [Endless-Horizon/CEV-Eris#503]
Оно не отображается ни в игре, ни в настройках в лобби на любом типе фигуры персонажа. Пробовал несколько штук рандомно, полагаю, что не работает ни один комплект.
На мой взгляд, стоит выпилить возможность выбора вообще. Куда проще, чем адаптировать еще сотню спрайтов под жирных и тощих.

**Comment by SpadesSlick** [comment]
Действительно, нужно ли нам это вообще.
