### ISSUE TITLE
Мне кажется, нам не нужно знать это

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#517]
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy Box of Sin-Pockets (JMP)
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy Agent ID card (JMP)
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy Power Sink (JMP)
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy Chameleon Kit (JMP)
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy Fully Loaded Toolbox (JMP)
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy 9mm (JMP)
ADMIN LOG: Valentine1488/(Alyson Stocker) used PDA-Alyson Stocker (Captain) to buy Random Items (JMP)

Бейское логирование сильно засоряет чат, и в наших более грифозных реалиях не нужно.

**Comment by SpadesSlick** [comment]
Вообще подобная проблема может проявится не только тут.

**Comment by fluorescent-net** [comment]
Sergeant Doe removes the magazine (9mm rubber) from FS SMG 9x19 "Sol".
Sergeant Doe inserts the magazine (9mm rubber) into FS SMG 9x19 "Sol".
Тоже очень спамит.
