### ISSUE TITLE
Четвертый понитейл сломан

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#534]
[Common] Alyson Stocker (follow) yells, "Крио украло мои волосы!"
to Valentine1488/(Alyson Stocker)(?): Что за прическа?
[Player PM] Valentine1488/(Alyson Stocker)(?): четвёртый понитейл

**Comment by AliaKhin** [comment]
Уже решено в https://github.com/Endless-Horizon/CEV-Eris/issues/505
