### ISSUE TITLE
Strange red pixel in 8 and 4 dirs on fat humans

### ISSUE THREAD

**Issue by Quardbreak** [Endless-Horizon/CEV-Eris#604]
![default](https://cloud.githubusercontent.com/assets/17644501/23711051/c2aa950e-042f-11e7-9f29-b9d218ef57b8.png)
![default](https://cloud.githubusercontent.com/assets/17644501/23711059/c7e89214-042f-11e7-8919-e62b5a599276.png)

**Comment by SpadesSlick** [comment]
Fixed.
