### ISSUE TITLE
Генератор гравитации

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#61]
По большей части тут нужно понять, какая его часть уже есть на Бее, и как лучше спиздить его с ТГ. Он так же должен адекватно работать с зет уровнями, включать и выключать гравитацию на все 5 этажей, не давать людям и вещам падать в опен спейс при выключенной гравитации, и подобное.

Наверное, было бы резонно при его включении проверять все опенспейсы, и ронять на пол то, что должно падать.

**Comment by Strinkor** [comment]
На грине он адаптирован под многоуровневость.
