### ISSUE TITLE
Овермап не может отображать диры турфов.

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#636]
![image](https://cloud.githubusercontent.com/assets/9161564/23961696/d0ed6582-09bc-11e7-9e76-f28901387cdd.png)
Я не уверен, нужно ли вообще использовать диры на турфах, так как вот этот конкретный - единственный который их использует. Я вполне мог бы реализовать все это через декали.

Тем менее, проблема есть.

**Comment by LethalGhost** [comment]
*Опенспейс
