### ISSUE TITLE
Problem with selecting bottom underwear 

### ISSUE THREAD

**Issue by Sharmount** [Endless-Horizon/CEV-Eris#736]
![4ffd0bd03f044cd6b5282734d12cbe2d](https://cloud.githubusercontent.com/assets/20283678/24852862/3decb4f8-1e03-11e7-8499-a02577587cce.png)

While we have two different sections for underwear, if you change top, bottom will be changed as well.

**Comment by SpadesSlick** [comment]
Closed by #788.
