### ISSUE TITLE
Voice actvation system are broken

### ISSUE THREAD

**Issue by SpadesSlick** [Endless-Horizon/CEV-Eris#769]
Some time ago, we fixed bug that kills entire server when someone shot from a gun, when a lot of mags was in view range. The reason was funny: after every shoot it searches in every magazine near to find mobs. Thats how stuff like hearing in closets worked.

While we fixed that problem with closets, looks like "voice actvation" stuff, like explosive implants, don't work now. It crucial for cruciform to work, so we need to fix that.

**Comment by fluorescent-net** [comment]
Fixed in #773.
